version: "3"
services:
  bot:
    build: .
    image: bot:latest
    ports:
      - 8000:80
    volumes:
      - '.:/src'
    environment:
      API_KEY: '534820315:AAHhiOAOnKW4Ml5yCymeJFhyaw21DgNhMMk'
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    command: mongod --journal --bind_ip 0.0.0.0
    environment:
      TZ: 'Europe/Moscow'
      SERVICE_TAGS: 'app'
    volumes:
      - "./mongo/data/db:/data/db"
    ports:
      - "0.0.0.0:27017:27017"

