version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    command: mongod --journal --bind_ip 0.0.0.0
    environment:
      TZ: 'Europe/Moscow'
      SERVICE_TAGS: 'app'
    volumes:
      - "./data/db:/data/db"
    ports:
      - "0.0.0.0:27017:27017"
